# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(help_text='上传留言文件', upload_to='message/images/', verbose_name='上传留言文件'),
        ),
    ]
