"""
Django settings for DianShop project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
#把apps等加入到环境变量
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# sys.path.insert(0,BASE_DIR)

#把apps，extra_apps添加到运行环境中
sys.path.insert(0,os.path.join(BASE_DIR,'apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))
# print("BASE_DIR==",BASE_DIR)
# print("sys.path[0]==",sys.path[0])
# print("sys.path[1]==",sys.path[1])
# print("sys.path[2]==",sys.path[2])



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 't!lx%1y^oh1bw8g!vovym#ej78l&e)o=v39+nm@e3!+xcr&1v5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
#替换系统的用户
AUTH_USER_MODEL = "users.UserProfile"

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',#用户
    'goods.apps.GoodsConfig',#商品
    'trade.apps.TradeConfig',#贸易
    'DjangoUeditor',
    'user_operation.apps.UserOperationConfig',#用户操作
    'xadmin',#xadmin注册
    'crispy_forms',#登录校验
    'rest_framework',
    'django_filters',
    'corsheaders',#支持跨域请求
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DianShop.urls'

#允许跨域请求
CORS_ORIGIN_ALLOW_ALL = True

#以后REST_FRAMEWORK的配置都在这里（drf分页）
REST_FRAMEWORK = {
    #配置分页的类
    'DEFAULT_PAGINATION_CLASS':"rest_framework.pagination.PageNumberPagination",
    'PAGE_SIZE':10,
    'DEFAULT_FILTER_BACKENDS':('django_filters.rest_framework.DjangoFilterBackend',)
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'django.contrib.messages.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'DianShop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tiantianshop',
        'USER':'root',
        'PASSWORD':12345,
        'HOST':'localhost',
        'port':3306,
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
#设置中文
LANGUAGE_CODE = 'zh-hans'
#设置时区
TIME_ZONE = 'Asia/Shanghai'
#国际化
USE_I18N = True

USE_L10N = True
#默认当前电脑的时间
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFTLES_DIRS = [
    os.path.join(BASE_DIR,'static')
]
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR,"media")