# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_sn',
            field=models.CharField(default='', max_length=50, verbose_name='商品编号'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='desc',
            field=models.TextField(help_text='品牌描述', max_length=100, verbose_name='品牌描述'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='name',
            field=models.CharField(help_text='品牌名字', max_length=30, verbose_name='品牌名字'),
        ),
    ]
