# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180731_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='goods/banner', verbose_name='轮播图片'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/goodsimages/', verbose_name='图片'),
        ),
    ]
